### ISSUE TITLE
QA_Image-Processing_Assessment_Image-Segmentation_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#100]
Defect Description :
In the Assessment section of Image Segmentation experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Assessment section of Image Segmentation experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i44](https://cloud.githubusercontent.com/assets/13479177/26096645/7b9473c4-3a3f-11e7-8625-32daf4ff6303.png)

**Comment by BSravanthi** [comment]
Resolved

**Comment by sravanthimodepu** [comment]
Closing ..
