### ISSUE TITLE
QA_Color Image Processing_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#14]
Defect Description :
In the "Colour Image Processing" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required               

Actual Result :
In the "Colour Image Processing" experiment, the minimum requirement to run the experiment is not displayed in the page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Color%20Image%20Processing/Color%20Image%20Processing_21_Prerequisites_p1.org

Attachment:
![ip32](https://cloud.githubusercontent.com/assets/14869397/14633656/3985e13a-063c-11e6-8b70-d63bd7541f69.png)

**Comment by sadhanareddy** [comment]
Based on discussion with Lalit, closing this issue.

**Comment by BSravanthi** [comment]
Closed the issue.
