### ISSUE TITLE
QA_Fourier Transform_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#18]
Defect Description :
In the "Fourier Transform" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required             

Actual Result :
In the "Fourier Transform" experiment, the minimum requirement to run the experiment is not displayed in the page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Fourier%20Transform/Fourier%20Transform_21_Prerequisites_p1.org

**Comment by sadhanareddy** [comment]
Based on discussion with Lalit, closing this issue.

**Comment by BSravanthi** [comment]
Closed the issue.
