### ISSUE TITLE
QA_Image Histogram_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#23]
Defect Description :
In the "Image Histogram" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user           

Actual Result :
In the "Image Histogram" experiment,the back to experiments link is not present in the page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Image%20Histogram/Image%20Histogram_20_Back%20to%20experiment_smk.org

Attachment:
![ip23](https://cloud.githubusercontent.com/assets/14869397/14633356/dfa4b066-063a-11e6-86b6-19dd395540c6.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
