### ISSUE TITLE
QA_Point Operations_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#31]
Defect Description :
In the "Point Operations" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user        

Actual Result :
In the "Point Operations" experiment,the back to experiments link is not present in the page 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Point%20Operations/Point%20Operations_24_Back%20to%20experiment_smk.org

Attachment:
![ip15](https://cloud.githubusercontent.com/assets/14869397/14632980/150e9f34-0639-11e6-9005-0b7f3888b24e.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
