### ISSUE TITLE
QA_Affine Transformation_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#36]
Defect Description :
In the experiment page of  "Affine Transformation" experiment, the scroll bar is not working instead the scroll bar should be enabled in-order to view the experiment result    

Actual Result :
In the experiment page of  "Affine Transformation" experiment, the scroll bar button is not working  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Affine%20Transformation/Affine%20Transformation_06_Experiment_smk.org

Attachment:
![ip10](https://cloud.githubusercontent.com/assets/14869397/14632773/17ee12c6-0638-11e6-89b8-2b7a5fa0ce98.png)

**Comment by sadhanareddy** [comment]
Differing this issue. Scroll bar will be enabled only for particular experiments. If there are too many images which are wrapped inside the box, then we can slide the scroll bar to see the images clearly. If the images are not wrapped, then the scroll bar will be disabled. Hence closing this issue.

**Comment by BSravanthi** [comment]
Closed the issue.
