### ISSUE TITLE
QA_Distance and Connectivity_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#43]
Defect Description :
In the "Distance and Connectivity" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user  

Actual Result :
In the "Distance and Connectivity" experiment,the back to experiments link is not present in the page 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Distance%20and%20Connectivity/Distance%20and%20Connectivity_17_Back%20to%20experiment_smk.org

Attachment:
![ip3](https://cloud.githubusercontent.com/assets/14869397/14630935/6124313c-062e-11e6-95b0-f673052b9586.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed
