### ISSUE TITLE
QA_Distance and Connectivity_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#44]
Defect Description :
In the experiment page of  "Distance and Connectivity" experiment, the scroll bar is not working instead the scroll bar should be enabled in-order to view the experiment result

Actual Result :In the experiment page of  "Distance and Connectivity" experiment, the scroll bar button is not working 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Distance%20and%20Connectivity/Distance%20and%20Connectivity_06_Experiment_smk.org

Attachment:
![ip2](https://cloud.githubusercontent.com/assets/14869397/14630907/3e8fb7ae-062e-11e6-8d7d-9d0ed8f87550.png)

**Comment by sadhanareddy** [comment]
Differing this issue. Scroll bar will be enabled only for particular experiments. If there are too many images which are wraped inside the box, then we can slide the scroll bar to see the images clearly. If the images are not wraped, then the scroll bar will be disabled. Hence closing this issue.

**Comment by BSravanthi** [comment]
Closed
