### ISSUE TITLE
QA_Introduction_smk

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#57]
Defect Description :
In the Introduction page of the lab, found spelling mistakes. 

Actual Result :
In the Introduction page of the lab, found spelling mistakes. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i01](https://cloud.githubusercontent.com/assets/13479177/25944888/819bc988-3662-11e7-89ce-89cc66330a92.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence resolving the issue.

**Comment by BSravanthi** [comment]
Fixed

![qa_oe_ip_i60](https://user-images.githubusercontent.com/13479177/27781145-4a46bd1a-5fea-11e7-9ed4-d9cb5fccd74a.png)

**Comment by sravanthimodepu** [comment]
Closing..
