### ISSUE TITLE
QA_Target Audience_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#58]
Defect Description :
In the Target Audience page of the lab, found spelling mistakes.

Actual Result :
In the Target Audience page of the lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i02](https://cloud.githubusercontent.com/assets/13479177/25945078/460829d8-3663-11e7-9d3d-5506d5ee5beb.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes

**Comment by BSravanthi** [comment]
Fixed

![qa_oe_ip_i59](https://user-images.githubusercontent.com/13479177/27781082-01b0a5b6-5fea-11e7-937b-28e5f9e107e7.png)

**Comment by sravanthimodepu** [comment]
Closing..
