### ISSUE TITLE
QA_Breadcrump_spelling-mistake

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#59]
Defect Description :
In the Objective page of the Distance and Connectivity experiment in this lab, observed that in "Bread crump" **Objective** is spelled as "Ojective".

Actual Result :
In the Objective page of the Distance and Connectivity experiment in this lab, observed that in "Bread crump" **Objective** is spelled as "Ojective".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i03](https://cloud.githubusercontent.com/assets/13479177/25945438/83f9f4f0-3664-11e7-881b-b6735126588c.png)

**Comment by BSravanthi** [comment]
Corrected

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i58](https://user-images.githubusercontent.com/13479177/27781030-c72d261c-5fe9-11e7-8739-b105cd05961e.png)

**Comment by sravanthimodepu** [comment]
Closing..
