### ISSUE TITLE
QA_Image-Processing_experiment_Image-Arithmetic_Experiment-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#62]
Defect Description :
In the experiment section of Image Arithmetic experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both full and small screens.

Actual Result :
In the experiment section of Image Arithmetic experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments: 
![qa_oe_ip_i07](https://cloud.githubusercontent.com/assets/13479177/26044057/8bb7c980-395f-11e7-9f2b-adf948144f8e.png)

**Comment by BSravanthi** [comment]
Resolved

**Comment by sravanthimodepu** [comment]
Closing..
