### ISSUE TITLE
QA_Image-Arithmetic_References_Broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#64]
Defect Description :
In the References page of the Distance Image Arithmetic experiment, the 2nd link is navigating to error page. 

Actual Result :
In the References page of the Distance Image Arithmetic experiment, found broken link. The 2nd link is navigating to error page. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_ip_i09](https://cloud.githubusercontent.com/assets/13479177/26044320/2f7dcd5c-3961-11e7-9aaa-5c942092de8c.png)

**Comment by BSravanthi** [comment]
Removed broken link.

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Still the link is existing in the page. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i57](https://user-images.githubusercontent.com/13479177/27780974-83000f7c-5fe9-11e7-9498-692de908dc6f.png)

**Comment by sravanthimodepu** [comment]
Closing..
