### ISSUE TITLE
QA_Image-Processing_Assessment_Image-Arithmetic_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#65]
Defect Description :
In the Assessment section of Image Arithmetic experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Assessment section of Image Arithmetic experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i10](https://cloud.githubusercontent.com/assets/13479177/26044406/c5ef9784-3961-11e7-99c6-ec3b73538518.png)

**Comment by BSravanthi** [comment]
Resolved

**Comment by sravanthimodepu** [comment]
Closing..
