### ISSUE TITLE
QA_Affine-Transformation_Theory_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#66]
Defect Description :
In the Theory page of the Affine Transformation experiment in this lab, found spelling mistakes.

Actual Result :
In the Theory page of the Affine Transformation experiment in this lab, found spelling mistakes. Refer to attachments. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i11](https://cloud.githubusercontent.com/assets/13479177/26044558/b728f73a-3962-11e7-922a-85a301907bac.png)

**Comment by BSravanthi** [comment]
Corrected spelling mistakes

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i56](https://user-images.githubusercontent.com/13479177/27778737-f2bdc1e2-5fda-11e7-8d15-3b0e2fc21abb.png)

**Comment by sravanthimodepu** [comment]
Closing..
