### ISSUE TITLE
QA_Image-Processing_experiment_Affine-Transformation_Experiment-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#67]
Defect Description :
In the experiment section of Affine Transformation experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both full and small screens.

Actual Result :
In the experiment section of Affine Transformation experiment, the experiment is disabled in the small screen. Instead, the experiment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i12](https://cloud.githubusercontent.com/assets/13479177/26050110/1c0918ac-397b-11e7-826b-ac6f3ee9a21c.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
