### ISSUE TITLE
QA_Affine-Transformation_References_Broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#69]
Defect Description :
In the References page of the Distance Affine Transformation experiment, the 7th link is navigating to error page.

Actual Result :
In the References page of the Distance Affine Transformation experiment, found broken link. The 7th link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_ip_i14](https://cloud.githubusercontent.com/assets/13479177/26050712/50908f2c-397d-11e7-8fe9-2ccf9b8db9e2.png)

**Comment by BSravanthi** [comment]
Removed the broken link

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed and the broken link is still existing in the page.

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i55](https://user-images.githubusercontent.com/13479177/27778700-a0e8a3e6-5fda-11e7-8197-d872e40e74d9.png)

**Comment by sravanthimodepu** [comment]
Closing..
