### ISSUE TITLE
QA_Affine-Transformation_References_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#70]
Defect Description :
In the References page of the Affine Transformation experiment in this lab, found spelling mistakes.

Actual Result :
In the References page of the Affine Transformation experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i15](https://cloud.githubusercontent.com/assets/13479177/26050814/bf756624-397d-11e7-973e-c22a6cd5fd58.png)

**Comment by BSravanthi** [comment]
Linking to #69

**Comment by BSravanthi** [comment]
As the link is removed from the references list. Deferring this issue.

**Comment by sravanthimodepu** [comment]
Closing..
