### ISSUE TITLE
QA_Point-Operations_Procedure_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#72]
Defect Description :
In the Theory page of the Point Operations experiment in this lab, found spelling mistakes.

Actual Result :
In the Theory page of the Point Operations experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i17](https://cloud.githubusercontent.com/assets/13479177/26051205/18e674ae-397f-11e7-8c1f-fdd6b87e8b9a.png)

**Comment by BSravanthi** [comment]
Corrected spelling mistakes

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.
![point](https://user-images.githubusercontent.com/11156924/27760813-f9af86b6-5e6d-11e7-880f-3aa9dabff26e.png)

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i54](https://user-images.githubusercontent.com/13479177/27778645-3d0c7ab4-5fda-11e7-86ac-900fafe9fbe3.png)

**Comment by sravanthimodepu** [comment]
Closing..
