### ISSUE TITLE
QA_Neighbourhood-Operations_Theory_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#77]
Defect Description :
In the Theory page of the Neighbourhood Operations experiment in this lab, found spelling mistakes.

Actual Result :
In the Theory page of the Neighbourhood Operations experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i22](https://cloud.githubusercontent.com/assets/13479177/26053651/3dcfb4ee-3987-11e7-838f-ea07031f2bc9.png)

**Comment by BSravanthi** [comment]
Corrected spelling mistakes.

**Comment by sravanthimodepu** [comment]
Not yet resolved the issue.Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i51](https://user-images.githubusercontent.com/13479177/27778466-b7c38aec-5fd8-11e7-8b03-09421ce75ab8.png)

**Comment by sravanthimodepu** [comment]
Closing..
