### ISSUE TITLE
QA_Image-Processing_Experiment_Neighbourhood-Operations_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#78]
Defect Description :
In the Experiment section of Neighbourhood Operations experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Experiment section of Neighbourhood Operations experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i23](https://cloud.githubusercontent.com/assets/13479177/26090237/289c05d8-3a21-11e7-84e6-14ca2b15dc97.png)

**Comment by BSravanthi** [comment]
Resolved

**Comment by sravanthimodepu** [comment]
Closing..
