### ISSUE TITLE
QA_Neighbourhood-Operations_References_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#81]
Defect Description :
In the References page of the Neighbourhood Operations experiment in this lab, found spelling mistakes.

Actual Result :
In the References page of the Neighbourhood Operations experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i26](https://cloud.githubusercontent.com/assets/13479177/26090408/65a1afcc-3a22-11e7-8a1c-2717f9fabf83.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Not yet resolved the issue. Hence reopening the issue.
![neigh-ref](https://user-images.githubusercontent.com/11156924/27744879-f3e325ba-5dde-11e7-8e37-b42ffe5e5da6.png)

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i50](https://user-images.githubusercontent.com/13479177/27778369-f2bf0582-5fd7-11e7-85d9-defe2353e6f5.png)

**Comment by sravanthimodepu** [comment]
Closing..
