### ISSUE TITLE
QA_Image-Processing_Assessment_Image-Histogram_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#84]
Defect Description :
In the Assessment section of Image Histogram experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Assessment section of Image Histogram experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i29](https://cloud.githubusercontent.com/assets/13479177/26090683/31a39b66-3a24-11e7-9bc0-d32b1661c349.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
