### ISSUE TITLE
QA_Image Histogram_References_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#85]
Defect Description :
In the References page of the Image Histogram experiment in this lab, found spelling mistakes.

Actual Result :
In the References page of the Image Histogram experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i30](https://cloud.githubusercontent.com/assets/13479177/26090735/760e51c4-3a24-11e7-88c6-8bcc4e354c0d.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Not yet resolved the issue. Hence reopening the issue.



![img-hist](https://user-images.githubusercontent.com/11156924/27743448-a8d54936-5dd9-11e7-80f4-028691732377.png)

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i49](https://user-images.githubusercontent.com/13479177/27778302-7348f7d6-5fd7-11e7-8fc1-b039af990013.png)

**Comment by sravanthimodepu** [comment]
Closing..
