### ISSUE TITLE
QA_Image-Processing_Assessment_Fourier-Transform_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#88]
Defect Description :
In the Assessment section of Fourier Transform experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Assessment section of Fourier Transform experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_im_i32](https://cloud.githubusercontent.com/assets/13479177/26092409/6b9bb77c-3a2e-11e7-83f0-a8d92debd9ce.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
