### ISSUE TITLE
QA_Image Segmentation_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/image-processing-iiith#9]
Defect Description :
In the landing page/home page of "Image Segmentation" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options                 

Actual Result :
In the landing page/home page of "Image Segmentation" experiment, the name of the experiment is not present in the screen 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/image-processing-iiith/blob/master/test-cases/integration_test-cases/Image%20Segmentation/Image%20Segmentation_01_Usability_smk.org

Attachment:
![ip37](https://cloud.githubusercontent.com/assets/14869397/14633792/d87f88b8-063c-11e6-9380-4816a4dcc373.png)

**Comment by sadhanareddy** [comment]
Differing this issue. Name of the experiment is present in every link, as this is a part of the design. Hence closing this issue.

**Comment by BSravanthi** [comment]
Closed the issue.
