### ISSUE TITLE
QA_Image-Processing_Assessment_Color-Image-Processing_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#91]
Defect Description :
In the Assessment section of Color Image Processing experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Assessment section of Color Image Processing experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i35](https://cloud.githubusercontent.com/assets/13479177/26093052/a7eaf884-3a31-11e7-823a-59935c524f65.png)

**Comment by BSravanthi** [comment]
Resloved

**Comment by sravanthimodepu** [comment]
Closing..
