### ISSUE TITLE
QA_Image-Processing_Experiment_Morphological-Operations_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#92]
Defect Description :
In the Experiment section of Morphological Operations experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the Experiment section of Morphological Operations experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ip_i36](https://cloud.githubusercontent.com/assets/13479177/26093199/7a5ed13c-3a32-11e7-8ec3-d6b5202a7ed6.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
