### ISSUE TITLE
QA_Morphological-Operations_Quiz_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#93]
Defect Description :
In the Quiz page of the Morphological Operations experiment in this lab, found spelling mistakes.

Actual Result :
In the Quiz page of the Morphological Operations experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i37](https://cloud.githubusercontent.com/assets/13479177/26093535/f32d6528-3a33-11e7-8e00-e25fcc422ae1.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Not yet resolved the issue. Hence reopening the issue.
![morp-quiz](https://user-images.githubusercontent.com/11156924/27742740-53865c9c-5dd7-11e7-837a-a334e9ab40b2.png)

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i48](https://user-images.githubusercontent.com/13479177/27778257-1083a380-5fd7-11e7-94f8-8037c84420ae.png)

**Comment by sravanthimodepu** [comment]
Closing..
