### ISSUE TITLE
QA_Morphological-Operations_References_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#96]
Defect Description :
In the References page of the Morphological Operations experiment in this lab, found spelling mistakes.

Actual Result :
In the References page of the Morphological Operations experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i40](https://cloud.githubusercontent.com/assets/13479177/26093894/4f5b4c10-3a35-11e7-8766-39c06d5b6e4c.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.
![moph-op](https://user-images.githubusercontent.com/11156924/27741931-5901b656-5dd4-11e7-9927-4eb0b6b3cde6.png)

**Comment by BSravanthi** [comment]
Fixed 

![qa_oe_ip_i47](https://user-images.githubusercontent.com/13479177/27778190-7dccd8f4-5fd6-11e7-8675-78358bb80cba.png)

**Comment by sravanthimodepu** [comment]
Closing..
