### ISSUE TITLE
QA_Image-Segmentation_Introduction_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#97]
Defect Description :
In the Introduction page of the Image Segmentation experiment in this lab, found spelling mistakes.

Actual Result :
In the Introduction page of the Image Segmentation experiment in this lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_ip_i41](https://cloud.githubusercontent.com/assets/13479177/26094024/db337816-3a35-11e7-80fb-a2e8b153c2c3.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Not yet corrected the spelling mistakes.. Hence reopening the issue.
![image-seg](https://user-images.githubusercontent.com/11156924/27740773-a7ef743c-5dd0-11e7-914d-128a8f67f55a.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
